version: 2.1
orbs:
  node: circleci/node@4.7.0
jobs:
  run-unit-tests:
    executor:
      name: node/16.13
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn run test -u --maxWorkers=1 --maxConcurrency=1 --silent
          name: Run tests
workflows:
  node-tests:
    jobs:
      - run-unit-tests
